### ISSUE TITLE
esekfom::esekf模板问题

### ISSUE THREAD

**Issue by 98huan** [zlwang7/S-FAST_LIO#3]
为什么使用esekfom::esekf时不用模板？我看FAST_LIO2里是esekfom::esekf<state_ikfom, 12, input_ikfom>，不用模板会有问题吗？

**Comment by zlwang7** [comment]
你好，为了简洁，我在定义 esekfom::esekf类 的时候把模板去掉了，所以不需要模板。在 esekfom.cpp 的37行
