### ISSUE TITLE
English version document

### ISSUE THREAD

**Issue by Kihoon-Shin** [zlwang7/S-FAST_LIO#5]
Hello Sir, Thank your FAST-LIO paper.
I found that the FAST-LIO paper that you provide is Chinese version only.
Could I get a Engilsh version of FAST-LIO paper?
Thank you

**Comment by zlwang7** [comment]
Hello, thank you for your affirmation. I don't have an English version here. Perhaps I can provide you with a PDF link and you can translate it into English yourself.

https://drive.google.com/file/d/1q0oVX6a_aW2qRcQMXBi-fQQUX4ftjRib/view
