### ISSUE TITLE
Sophus版本问题

### ISSUE THREAD

**Issue by NHMMing** [zlwang7/S-FAST_LIO#9]
王博您好，感谢您开源的S-FAST-LIO。
在按照readme中的安装方法安装Sophus时遇到了问题，git checkout a621ff后，编译失败，报错是存在一个非法左值赋值。用最新分支main-1.x的最新commit编译后，Sophus安装成功。但是在编译S-FAST-LIO时发现引用头文件时名称不一致（估计是Sophus不一致导致的）导致报错。看报错都是代码里使用Sophus::SO3时与我安装的Sophus版本不一致。
我想知道您的源代码具体用的是Sophus哪个分支的哪个commit编译的，期待您的回复

**Comment by ouguangjun** [comment]
我刚刚也遇到你的问题，我现在解决了。

关于编译sophus报错的  左值赋值：
把so2.cpp文件该成如下：

SO2::SO2()
{
  unit_complex_.real(1.);
  unit_complex_.imag(0.);
}

就是把数值放在括号里。

关于Sophus::SO3报错，可以在cmakelist.txt 里 在 “find_package( Sophus REQUIRED )”后面一行加上

set(Sophus_LIBRARIES "/home/jason/Downloads/Sophus/build/libSophus.so")

这里的so文件地址换成你build文件地址就行

**Comment by NHMMing** [comment]
> 我刚刚也遇到你的问题，我现在解决了。
> 
> 关于编译sophus报错的 左值赋值： 把so2.cpp文件该成如下：
> 
> SO2::SO2() { unit_complex_.real(1.); unit_complex_.imag(0.); }
> 
> 就是把数值放在括号里。
> 
> 关于Sophus::SO3报错，可以在cmakelist.txt 里 在 “find_package( Sophus REQUIRED )”后面一行加上
> 
> set(Sophus_LIBRARIES "/home/jason/Downloads/Sophus/build/libSophus.so")
> 
> 这里的so文件地址换成你build文件地址就行

十分感谢你的回答！so2的错误之前我也用同样的方法解决了，忘记更新，实在不好意思。so3的问题我后续按照你的方法跟进一下。再次感谢！
